CONFIG_NAME=HCMUT-DKMH
CONFIG_VERSION=1.0

PORT=443
HTTPS=true

USER_AGENT=BRegClient/1.0

AUTH_SERVICE=cas-sso
AUTH_SERVICE_HOSTNAME=sso.hcmut.edu.vn
AUTH_SERVICE_PATH=/cas/login
AUTH_SERVICE_URL=https://sso.hcmut.edu.vn/cas/login
AUTH_SERVICE_TOKEN_NAME=CASTGC
AUTH_SERVICE_QUERY_SERVICE_NAME=service
AUTH_SERVICE_QUERY_RESPONSE_TICKET_NAME=ticket

TARGET_SERVICE=https://mybk.hcmut.edu.vn/dkmh/home.action
TARGET_SERVICE_HOSTNAME=mybk.hcmut.edu.vn
TARGET_SERVICE_PATH=/dkmh
TARGET_SERVICE_URL=https://mybk.hcmut.edu.vn/dkmh
TARGET_SERVICE_AUTH_PATH=/dkmh/home.action
TARGET_SERVICE_TICKET_NAME=ticket
TARGET_SERVICE_SESSION_NAME=JSESSIONID

TARGET_FETCH_ROUNDS_PATH=/dkmh/dangKyMonHocForm.action
TARGET_FETCH_SEEDS_PATH=/dkmh/getDanhSachDotDK.action
TARGET_SWITCH_ROUND_PATH=/dkmh/getDanhSachDotDK.action
TARGET_SWITCH_SEED_PATH=/dkmh/getLichDangKy.action
TARGET_REGISTER_PATH=/dkmh/dangKy.action
TARGET_UNREGISTER_PATH=/dkmh/huyDangKy.action
TARGET_FETCH_ENROLLMENTS_PATH=/dkmh/getKetQuaDangKy.action
TARGET_FETCH_COURSES_PATH=/dkmh/searchMonHocDangKy.action
TARGET_FETCH_CLASSES_PATH=/dkmh/getThongTinNhomLopMonHoc.action

ROUND_NAME=hocKyId
SEED_NAME=dotDKId
COURSE_CODE_NAME=msmh
COURSE_ID_NAME=monHocId
CLASS_ID_NAME=NLMHId
ENROLLMENT_ID_NAME=ketquaId

DB_SQLITE_CACHE_PATH=./hcmut-dkmh_cache.db
DB_SQLITE_ENROLLMENT_PATH=./hcmut-dkmh_enrollment.db