[GENERAL]
CONFIG_NAME=HCMUT-DKMH
CONFIG_VERSION=1.0

PORT=443
HTTPS=true

USER_AGENT=BRegClient/1.0

[SERVICE AUTHENTICATION]
NAME=cas-sso
HOSTNAME=sso.hcmut.edu.vn
PATH=/cas/login
URL=https://sso.hcmut.edu.vn/cas/login
TOKEN_NAME=CASTGC
QUERY_SERVICE_NAME=service
QUERY_RESPONSE_TICKET_NAME=ticket

[SERVICE TARGET]
NAME=https://mybk.hcmut.edu.vn/dkmh/home.action
HOSTNAME=mybk.hcmut.edu.vn
PATH=/dkmh
URL=https://mybk.hcmut.edu.vn/dkmh
AUTH_PATH=/dkmh/home.action
TICKET_NAME=ticket
SESSION_NAME=JSESSIONID

FETCH_ROUNDS_PATH=/dkmh/dangKyMonHocForm.action
FETCH_SEEDS_PATH=/dkmh/getDanhSachDotDK.action
SWITCH_ROUND_PATH=/dkmh/getDanhSachDotDK.action
SWITCH_SEED_PATH=/dkmh/getLichDangKy.action
REGISTER_PATH=/dkmh/dangKy.action
UNREGISTER_PATH=/dkmh/huyDangKy.action
FETCH_ENROLLMENTS_PATH=/dkmh/getKetQuaDangKy.action
FETCH_COURSES_PATH=/dkmh/searchMonHocDangKy.action
FETCH_CLASSES_PATH=/dkmh/getThongTinNhomLopMonHoc.action

[NAME NETWORK]
ROUND=hocKyId
SEED=dotDKId
COURSE_CODE=msmh
COURSE_ID=monHocId
CLASS_ID=NLMHId
ENROLLMENT_ID=ketquaId

[DATABASE SQLITE]
CACHE_PATH=./hcmut-dkmh_cache.db
ENROLLMENT_PATH=./hcmut-dkmh_enrollment.db